- hosts: dgx_pod_all_fabrics
  name: startup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: cp api_file
      copy:
        src: /home/cumulus/DGX/.nvue/api_file
        dest: /home/cumulus
    - name: run it
      shell: sudo bash /home/cumulus/api_file
